package tprestaurant.model.enums;

public enum Provincias {
    Buenos_Aires,
    Santa_Fe,
    Cordoba,
    Santa_Cruz,
    Entre_Rios,
    Misiones,
    Corrientes,
    La_Pampa,
    La_Rioja,
    San_Juan,
    Mendoza,
    Santiago_Del_Estero,
    Jujuy,
    Salta,
    Formosa,
    Chubut,
    Tierra_del_Fuego,
    Neuquen,
    Catamarca,
    Rio_Negro,
    Tucuman,
    Chaco,
    San_Luis,
}
